# Generated by Django 3.0.3 on 2020-02-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.CharField(choices=[('web', 'Web developer'), ('mobile', 'Mobile app developer')], default='web', max_length=6),
        ),
    ]
